app:
  name: "Medix BE"
  port: "8080"

jwt:
  secret: "change-this-secret-in-production"

database:
  host: localhost
  port: 5432
  username: postgres
  password: password
  name: medix
  ssl: disable

migration_path: "file://migrations/data"
